# Generated by Django 4.0.5 on 2023-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emotions",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("Id", models.IntegerField(primary_key=True, serialize=False)),
                ("emotion", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "emotions",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("Id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "employess",
            },
        ),
    ]
